---
title: "Accessing yummly.com API with YummlyR"
author: "Roman Tsegelskyi"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Accessing yummly.com API with YummlyR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(collapse = T, comment = "#>")
library(yummlyr)
```

## Indroduction

Yummly.com is one of the world’s largest and most powerful recipe search site. Moreover, it more or less consistent API endpoints for searching and retreiving recipes and this packages aims to provide R bindings for those endpoints. 

This document is not intended to be exhaustive nor comprehensive but rather
a brief introduction to some of the more common bits of functionality and some
basic examples of how they can be used.

## Usage

First of all, obtain an API credentials from [Yummly.com](https://developer.yummly.com/).

After that you can use `save_yummly_credentials` to presist the `application ID` and `application key` between querries, or supply the directly to `search_recipes` and `get_recipe` functions.

### Search Recipes

`search_recipes` function corresponds to [Search Recipes API call](https://developer.yummly.com/documentation#) and is used to search for recipes fitting certain criterias. [Example search response](https://developer.yummly.com/documentation/search-recipes-response-sample). Simplest call looks like this:

    search_recipes('bacon')

YummlyR supports wide variety of criterias:

-   `require_pictures` set to TRUE if only to return recipes with photos
-   `allowed_ingredient` ingredient that all search results must include
-   `excluded_ingredient` ingredient that all search results should not contain
-   `allowed_diet` search results will only include recipes whose ingredients are allowed for that diet
-   `allowed_allergy` only include recipes whose ingredients are allowed for that allergy
-   `allowed_cuisine` search results will only include recipes with that cuisine
-   `excluded_cuisine` search results will only exclude recipes with that cuisine
-   `allowed_course` search results will only include recipes with that cuisine
-   `excluded_course` search results will only exclude recipes with that cuisine
-   `excluded_holiday` search results will only exclude recipes with that holiday
-   `max_total_time` search for recipes that do not exceed a specified max total cook + prep time in seconds
-   `max_results` number of results to return
-   `start` start with specific result in search
-   `nutrition` set the range of allowed values for a given nutrition attribute (see below for the list of supported nutrition attributes) by setting a min and/or a max
-   `flavor` set the ranges for taste attributes (this corresponds to the taste sliders on the Yummly.com search page). The values of min and max are between 0 and 1.
-   `facet_field` facet counts for ingredient and diet. When this parameter is called, the response will include a facetCounts object that lists the matching diets or ingredients and how many results match each diet or ingredient.

For example,

    search_recipes("onion soup", allowed_ingredient = "bacon")

will return onion soup recipes that have bacon as one of the ingredients. More detailed expanations of Yummly's Search API with example can be found [here](https://developer.yummly.com/documentation#).

**NOTE**: Allowed values for `ingeredient`, `diet`, `allergy`, `cuisine`, `course`, `holiday`, `nutrition` and `flavor` are defined by [Yummly.com metadata](https://developer.yummly.com/documentation#Metadata) and saved inside the package for convenience. Available metadata can be accessed using `get_metadata` function, for example,

    get_metadata('holiday')

will return you `data.frame` with information about available `holiday` keywords.

### Get Recipe

Fetch a recipe by its recipe ID. [Example recipe response](https://developer.yummly.com/documentation/get-recipe-response-sample). For example,

    get_recipe("French-Onion-Soup-The-Pioneer-Woman-Cooks-_-Ree-Drummond-41364")

returns a detailed information about [French Onion Soup French Onion Soup](https://www.yummly.com/recipe/French-Onion-Soup-1332461).
